global using CashFlow.Domain.Abstractions.Repositories;
global using CashFlow.Domain.Abstractions.Repositories.Expenses;
global using CashFlow.Domain.Abstractions.Repositories.User;
global using CashFlow.Domain.Abstractions.Security.Cryptograpy;
global using CashFlow.Domain.Abstractions.Security.Tokens;
global using CashFlow.Domain.Entities;
global using CashFlow.Infrastructure.DataAccess;
global using CashFlow.Infrastructure.DataAccess.Repositories;
global using CashFlow.Infrastructure.Extensions;
global using CashFlow.Infrastructure.Security.Tokens;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using CashFlow.Domain.Services.LoggedUser;
global using BC = BCrypt.Net.BCrypt;

